src/OMPService/OMPService/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "伟仕云安ITSM后台管理"
admin.site.site_title = "伟仕云安ITSM后台管理"
admin.site.site_url = None


api_patterns = [
        url(r'', include('itsm.urls')),
        url(r'', include('api.urls')),
        ]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^itsm/', include('itsm.urls')),
    url(r'^asset/', include('asset.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', include('itsm.urls')),
    url(r'^rest/', include(api_patterns, namespace='rest_api', app_name='ops')),
]

src/OMPService/api/urls.py
from django.conf.urls import url
from django.conf.urls import include
from rest_framework import routers
# from rest_framework.documentation import include_docs_urls

from .viewsets import AlertViewSet
from .viewsets import DeployInstanceViewSet

router = routers.DefaultRouter()

router.register("alert", AlertViewSet, base_name="AlertViewSet")
router.register("deploy", DeployInstanceViewSet, base_name="DeployInstanceViewSet")


urlpatterns = [
    url(r'', include(router.urls, namespace='api')),
    # url(r'^docs/', include_docs_urls(title='My API title')),
]

src/OMPService/itsm/urls.py
from django.conf.urls import url
from django.conf.urls import include
from rest_framework import routers

from .viewsets import EventViewSet
from .views import index
from .views import request_list
from .views import events
from .views import incident_list
from .views import event_detail
from .views import event_add
from .views import event_create_order
from .views import event_to_change
from .views import event_to_issue
from .views import event_upgrade
from .views import event_to_close
from .views import changes
from .views import change_detail
from .views import change_add
from .views import change_to_config
from .views import change_close
from .views import flow_pass
from .views import change_reject_back
from .views import issues
from .views import issue_detail
from .views import issue_close
from .views import issue_upgrade
from .views import issue_to_knowledge
from .views import releases
from .views import release_detail
from .views import knowledges
from .views import sla_dashboard
from .views import sla_event_dash
from .views import sla_change_dash
from .views import sla_issue_dash
from .views import sla_release_dash
from .views import knowledge_detail
from .views import user_confirm
from .views import user_confirm_accept
from .views import user_confirm_reject
from .views import satisfaction_log
from .views import config
from .views import config_overview
from .views import get_vm_list
from .views import get_disk_list
from .views import get_product_list
from .views import get_cluster_list
from .views import get_cluster_role_list
from .views import order_create
from .views import order_get
from .views import user_get
from .views import get_instance_list
from .views import resource_info
from .views import get_department_name_list


router = routers.DefaultRouter()

router.register("event", EventViewSet, base_name="EventViewSet")


urlpatterns = [
    url(r'^rest/', include(router.urls)),
    url(r'^$', index),

    # 事件管理
    url(r'^event_list/$', events),
    url(r'^request_list/$', request_list),
    url(r'^incident_list/$', incident_list),
    url(r'^event/(?P<pk>\d{1,9})', event_detail),
    url(r'^events/add/$', event_add),
    url(r'^events/create_order/(?P<pk>\d{1,9})', event_create_order),
    url(r'^events/event_to_change/(?P<pk>\d{1,9})', event_to_change),
    url(r'^events/event_to_issue/(?P<pk>\d{1,9})', event_to_issue),
    url(r'^events/event_upgrade/$', event_upgrade),
    url(r'^events/close/(?P<pk>\d{1,9})', event_to_close),

    # 变更管理
    url(r'^change_list/$', changes),
    url(r'^change/(?P<pk>\d{1,9})', change_detail),
    url(r'^change/pass/$', flow_pass),
    url(r'^change/reject/$', change_reject_back),
    url(r'^changes/add/$', change_add),
    url(r'^changes/change_to_config/(?P<pk>\d{1,9})', change_to_config),
    url(r'^changes/close/(?P<pk>\d{1,9})', change_close),

    # 问题管理
    url(r'^issue_list/$', issues),
    url(r'^issue/(?P<pk>\d{1,9})', issue_detail),
    url(r'^issue/close/(?P<pk>\d{1,9})', issue_close),
    url(r'^issue/upgrade/$', issue_upgrade),
    url(r'^issue/issue_to_knowledge/$', issue_to_knowledge),

    # 配置管理
    url(r'^config/$', config),
    url(r'^config/get_department_name_list/$', get_department_name_list),
    url(r'^config_overview/$', config_overview),


    # 发布管理
    url(r'^release_list/$', releases),
    url(r'^release/(?P<pk>\d{1,9})', release_detail),

    # 知识库管理
    url(r'^knowledge_list/$', knowledges),
    url(r'^knowledge/(?P<pk>\d{1,9})', knowledge_detail),

    # sla管理
    url(r'^sla/$', sla_dashboard),
    url(r'^sla/event_dash/$', sla_event_dash),
    url(r'^sla/issue_dash/$', sla_issue_dash),
    url(r'^sla/change_dash/$', sla_change_dash),
    url(r'^sla/release_dash/$', sla_release_dash),

    # CMDB
    url(r'cmdb/query_vm/$', get_vm_list),
    url(r'cmdb/query_disk/$', get_disk_list),

    # cloud config
    url(r'cloud/get_product_list/$', get_product_list),
    url(r'cloud/get_cluster_list/$', get_cluster_list),
    url(r'cloud/get_cluster_role_list/$', get_cluster_role_list),
    url(r'cloud/order_create/$', order_create),
    url(r'cloud/order_get/$', order_get),
    url(r'cloud/user_get/$', user_get),
    url(r'cloud/get_instance_list/$', get_instance_list),
    url(r'cloud/resource_info/$', resource_info),

    # message alert
    url(r'^user_confirm/(?P<pk>\d{1,9})', user_confirm),
    url(r'^user_confirm/accept/', user_confirm_accept),
    url(r'^user_confirm/reject/', user_confirm_accept),

    # 满意度
    url(r'^satisfaction/', satisfaction_log),
]

src/OMPService/itsm/models.py
import jsonfield

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import User
from django.core.cache import cache

from lib.models import BaseModel
from cloudres.models import VMInstance


event_module = {"flow": [{"node": 0, "name": "开始"}, {"node": 1, "notify": "邮件", "name": "部门主管"}, {"node": 2, "name": "结束"}], "name": "事件审批"}
change_module = {"flow": [{"node": 0, "name": "开始"}, {"node": 1, "notify": "邮件", "name": "部门主管"}, {"node": 2, "name": "结束"}], "name": "变更审批"}
release_module = {"flow": [{"node": 0, "name": "开始"}, {"node": 1, "notify": "邮件", "name": "部门主管"}, {"node": 2, "name": "结束"}], "name": "发布审批"}
issue_module = {"flow": [{"node": 0, "name": "开始"}, {"node": 1, "notify": "邮件", "name": "部门主管"}, {"node": 2, "name": "结束"}], "name": "问题审批"}
department = {"department": []}


class Event(BaseModel):

    EVENT_CHOICE = (
        ("draft", "草稿"),
        ("processing", "处理中"),
        ("issued", "转入问题"),
        ("changed", "转入变更"),
        ("checked", "审批完成"),
        ("ended", "结束")
    )

    EMERGENCY_DEGREE = (
        ("P1", "P1"),
        ("P2", "P2"),
        ("P3", "P3")
    )

    TYPE = (
        ("incident", "故障报修"),
        ("request", "服务请求"),
        ("s", "软件配置"),
        ("h", "系统维护"),
        ("n", "网络配置"),
    )

    name = models.CharField(max_length=128, verbose_name="事件名称", null=True, blank=True)
    description = models.TextField(verbose_name="事件描述", null=True, blank=True)
    state = models.CharField(max_length=128, choices=EVENT_CHOICE, verbose_name="事件状态", null=True, blank=True)
    initiator = models.CharField("发起人", max_length=128, null=True, blank=True)
    initiator_phone = models.CharField("发起人电话", max_length=128, null=True, blank=True)
    initiator_email = models.CharField("发起人邮箱", max_length=128, null=True, blank=True)
    initiator_channel = models.CharField("发起人渠道", max_length=128, null=True, blank=True)
    department = models.CharField(max_length=128, verbose_name="部门", null=True, blank=True)
    technician = models.ForeignKey(
        User, verbose_name="处理人", null=True, blank=True
    )
    emergency_degree = models.CharField(
        verbose_name="紧急度", choices=EMERGENCY_DEGREE, max_length=128, null=True, blank=True
    )
    service_level = models.CharField(verbose_name="SLA", max_length=128, null=True, blank=True)
    event_type = models.CharField(
        max_length=128, verbose_name="事件类型", choices=TYPE, null=True, blank=True
    )
    resource = models.CharField(max_length=128, verbose_name="事件源", null=True, blank=True)
    solution = models.TextField(verbose_name="解决方法", null=True, blank=True)
    attach_file = models.FileField(verbose_name="附件", null=True, blank=True)
    flow_module = models.FileField(verbose_name="流程模板", null=True, blank=True)
    cloud_order = models.CharField(verbose_name="云管订单", max_length=128, null=True, blank=True)
    cloud_order_ended = models.BooleanField("订单已完成", default=0)
    app_name = models.CharField("产品名称", max_length=128, null=True, blank=True)
    auto_deploy = models.BooleanField("是否自动化部署订单", default=0)
    leak_checked = models.BooleanField("是否执行漏洞扫描", default=0)
    late_flag = models.BooleanField("是否逾期", default=0)
    instance_id = models.IntegerField("云管实例ID", null=True, blank=True)

    def __str__(self):
        return self.name or ""

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        name = self.app_name
        query_set = ProductInfo.objects.filter(app_name=name).values("app_name")
        app_name_list = [i["app_name"] for i in query_set]
        if name in app_name_list:
            self.auto_deploy = 1
        super(Event, self).save(*args, **kwargs)


class Issue(BaseModel):

    name = models.CharField(max_length=128, verbose_name="问题名称")
    description = models.TextField(verbose_name="问题描述")
    state = models.CharField(max_length=128, verbose_name="问题状态")
    issue_type = models.CharField(max_length=128, null=True, blank=True, verbose_name="类型")
    handler = models.ForeignKey(User, verbose_name="处理人", null=True, blank=True)
    event_from = models.ForeignKey(Event, null=True, blank=True, verbose_name="事件源")
    solution = models.TextField(verbose_name="解决方法")
    attach_file = models.FileField(verbose_name="附件", null=True, blank=True)


class Change(BaseModel):
    EMERGENCY_DEGREE = (
        ("P1", "P1"),
        ("P2", "P2"),
        ("P3", "P3"),
    )

    STATE = (
        ("draft", "草稿"),
        ("ing", "流转中"),
        ("ended", "结束"),
        ("failed", "失败"),
    )

    name = models.CharField(max_length=129, verbose_name="变更名称", null=True, blank=True)
    description = models.TextField(verbose_name="变更描述")
    state = models.CharField(max_length=128, choices=STATE, default="draft", verbose_name="变更状态")
    initiator = models.CharField(max_length=128, null=True, blank=True, verbose_name="发起人")
    department = models.CharField(max_length=128, verbose_name="部门", null=True, blank=True)
    event = models.ForeignKey(Event, null=True, blank=True, verbose_name="关联事件")
    node_name = models.CharField(max_length=128, verbose_name="流程节点", null=True, blank=True)
    node_handler = models.ForeignKey(User, verbose_name="环节处理人", null=True, blank=True)
    emergency_degree = models.CharField(
        verbose_name="紧急度", max_length=128, null=True, blank=True,
    )
    service_level = models.CharField(verbose_name="SLA", max_length=128, null=True, blank=True)
    approver = models.CharField(verbose_name="变更评审", max_length=128, null=True, blank=True)
    # event_from = models.ForeignKey(VMInstance, null=True, blank=True, verbose_name="事件源")
    solution = models.TextField(verbose_name="解决方法", null=True, blank=True)
    online_plan = models.FileField(verbose_name="上线计划", null=True, blank=True)
    rollback_plan = models.FileField(verbose_name="回滚计划", null=True, blank=True)
    flow_node = models.IntegerField(verbose_name="当前流程节点", default=0)
    flow_module = models.CharField(verbose_name="流程模板", max_length=128, null=True, blank=True)
    leak_checked = models.BooleanField("漏洞扫描", default=0)

    def __str__(self):
        return self.name or ""


class Release(BaseModel):
    STAGE = (
        ("draft", "发起"),
        ("ing", "执行中"),
        ("end", "结束"),
        ("failed", "失败"),
    )
    name = models.CharField("发布名称", max_length=128)
    change = models.ForeignKey(Change, verbose_name="关联变更")
    stage = models.CharField("发布阶段", max_length=128, choices=STAGE)
    initiator = models.CharField("发起人", max_length=128, null=True, blank=True)
    technician = models.ForeignKey(User, max_length=128, verbose_name="处理人", null=True, blank=True)


class Knowledge(BaseModel):

    title = models.CharField("名称", max_length=128)
    issue_id = models.IntegerField("问题ID", null=True, blank=True)
    issue_name = models.CharField("问题名称", max_length=128, null=True, blank=True)
    classify = models.CharField("分类", max_length=128, null=True, blank=True)
    state = models.BooleanField("状态", default=0)
    content = models.TextField("内容")
    creater = models.CharField("创建人", max_length=128, null=True, blank=True)
    creater_id = models.IntegerField("创建人ID", null=True, blank=True)
    public_flag = models.IntegerField("是否公开", default=0)
    attach_file = models.FileField("附件", null=True, blank=True)

    def __str__(self):
        return self.title


class Config(BaseModel):

    name = models.CharField(max_length=128, verbose_name="名称")
    description = models.TextField(verbose_name="描述", null=True, blank=True)
    state = models.BooleanField(max_length=128, verbose_name="状态", default=1)
    # handler = models.CharField(max_length=128, verbose_name="处理人")
    # event_from = models.ForeignKey(VMInstance, null=True, blank=True, verbose_name="事件源")
    # solution = models.TextField(verbose_name="解决方法")
    attach_file = models.FileField(verbose_name="附件", null=True, blank=True)
    event_module = jsonfield.JSONField(verbose_name="事件模板", null=True, blank=True, default=event_module)
    issue_module = jsonfield.JSONField(verbose_name="问题模板", null=True, blank=True, default=issue_module)
    change_module = jsonfield.JSONField(verbose_name="变更模板", null=True, blank=True, default=change_module)
    sla_module = jsonfield.JSONField(verbose_name="sla配置", null=True, blank=True)
    department = jsonfield.JSONField("部门维护", null=True, blank=True, default=department)

    def __str__(self):
        return self.name


class TimeTree(BaseModel):

    # generic relations
    username = models.CharField(max_length=128, null=True, blank=True, verbose_name="操作人")
    userid = models.IntegerField(verbose_name="操作人ID", null=True, blank=True)
    action = models.CharField(max_length=128, null=True, blank=True, verbose_name="操作")
    CONTENT_TYPE_LIMIT = models.Q(app_label="itsm", model="event"
                                  ) | models.Q(app_label="itsm", model="config")
    content_type = models.ForeignKey("contenttypes.ContentType", limit_choices_to=CONTENT_TYPE_LIMIT,
                                     verbose_name="content type", blank=True, null=True, editable=False)
    object_uuid = models.UUIDField(verbose_name="object uuid", editable=True, blank=True, null=True)
    content_object = GenericForeignKey("content_type", "object_uuid")


class Sla(BaseModel):
    pass


class ProductInfo(BaseModel):

    app_name = models.CharField("应用名称", max_length=128)
    product_id = models.CharField("云管产品ID", max_length=128, default=0)
    cloud_flag = models.CharField("云归属", max_length=128, default=0)
    standard = jsonfield.JSONField("规格", null=True, blank=True)
    vswitch = models.CharField("网络组", max_length=128, null=True, blank=True)

    def __str__(self):
        return self.app_name


class EventProcessLog(BaseModel):

    event_obj = models.ForeignKey(Event, related_name="logs", verbose_name="关联事件")
    username = models.CharField("用户名", max_length=256, blank=True, null=True)

src/OMPService/templates/itsm/change_list.html
{% extends "base.html" %}
{% block header %}
    <li class="active">{{ page_header }}</li>
{% endblock %}
{% block PHeader %}
<h1>
    变更列表
</h1>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-xs-12">
        <!-- /.box -->
        <div class="box">
            <div class="box-header">
                <a href="/admin/itsm/change/add/"><i class="glyphicon glyphicon-plus"></i><span>新增变更</span></a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="dataTables_length" id="example1_length"><label>Show <select
                                    name="example1_length" aria-controls="example1" class="form-control input-sm">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select> entries</label></div>
                        </div>
                        <div class="col-sm-6">
                            <div id="example1_filter" class="dataTables_filter"><label>Search:<input type="search"
                                                                                                     class="form-control input-sm"
                                                                                                     placeholder=""
                                                                                                     aria-controls="example1"></label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example1" class="table table-bordered table-striped dataTable" role="grid"
                                   aria-describedby="example1_info">
                                <thead>
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">
                                        变更名称
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">
                                        变更状态
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">
                                        处理人
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">
                                        变更类型
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">
                                        创建时间
                                    </th>
                                </tr>
                                </thead>
                                {% for i in data %}
                                <tbody>
                                <tr role="row" class="odd">
                                    <td class="sorting_1"><a href="/itsm/change/{{ i.id }}">{{ i.name }}</a></td>
                                    <td class="sorting_1">{{ i.get_state_display }}</td>
                                    <td class="sorting_1">{{ i.node_handler.username }}</td>
                                    <td class="sorting_1">{{ i.event.get_event_type_display }}</td>
                                    <td class="sorting_1">{{ i.dt_created }}</td>
                                </tr>
                                </tbody>
                                {% endfor %}
                                <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1"></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing 1
                                to 10 of {{ count }} entries
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                <ul class="pagination">
                                    <li class="paginate_button previous disabled" id="example1_previous"><a href="#"
                                                                                                            aria-controls="example1"
                                                                                                            data-dt-idx="0"
                                                                                                            tabindex="0">Previous</a>
                                    </li>
                                    <li class="paginate_button active"><a href="#" aria-controls="example1"
                                                                          data-dt-idx="1" tabindex="0">1</a></li>
                                    <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="2"
                                                                    tabindex="0">2</a></li>
                                    <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="3"
                                                                    tabindex="0">3</a></li>
                                    <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="4"
                                                                    tabindex="0">4</a></li>
                                    <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="5"
                                                                    tabindex="0">5</a></li>
                                    <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="6"
                                                                    tabindex="0">6</a></li>
                                    <li class="paginate_button next" id="example1_next"><a href="#"
                                                                                           aria-controls="example1"
                                                                                           data-dt-idx="7" tabindex="0">Next</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
{% endblock %}

src/OMPService/templates/itsm/config.html
{% extends "base.html" %}
{% block head %}
    <script src="/static/js/this_config.js"></script>
{% endblock %}
{% block PHeader %}
    <h1>
        配置管理
    </h1>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="/static/js/img/vstecs.png" alt="logo">

              <h3 class="profile-username text-center">{{ org_name }}</h3>

              <ul class="list-group list-group-item-success">
                <li class="list-group-item">
                  <a href="#department_config" data-toggle="tab">部门维护</a>
                </li>
{#                <li class="list-group-item">#}
{#                  <a href="#flow_module" data-toggle="tab">工作流模板</a>#}
{#                </li>#}
{#                <li class="list-group-item">#}
{#                  <a href="#flow_module" data-toggle="tab">事件紧急度</a>#}
{#                </li>#}
{#                <li class="list-group-item">#}
{#                  <a href="#event_type" data-toggle="tab">事件类型</a>#}
{#                </li>#}
{#                <li class="list-group-item">#}
{#                  <a href="#event_status" data-toggle="tab">事件状态</a>#}
{#                </li>#}
{#                <li class="list-group-item">#}
{#                  <a href="#change_type" data-toggle="tab">变更类型</a>#}
{#                </li>#}
                <li class="list-group-item">
                  <a href="#sla_conf" data-toggle="tab">SLA配置</a>
                </li>
                <li class="list-group-item">
                  <a href="#overview" data-toggle="tab" id="all">配置总览</a>
                </li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            {% include "itsm/config_tabs.html" %}
        </div>
        <!-- /.col -->
      </div>
{% endblock %}

src/OMPService/templates/itsm/log_errors.html
<div class="pad margin no-print">
  <div class="callout callout-warning" style="margin-bottom: 0!important;">
    <h4><i class="fa fa-warning"></i> Note:</h4>
    {{ message }}
  </div>
</div>

src/OMPService/templates/itsm/new_change_detail.html
{% extends "base.html" %}
{% block head %}
    <script src="/static/bower_components/ckeditor/ckeditor.js"></script>
    <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1')
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>


{% endblock %}
{% block header %}
    <li class="active">{{ page_header }}</li>
{% endblock %}
{% block content %}
<section class="invoice">
    <!-- title row -->
    <form action="/itsm/change/add/" method="POST">
    <div class="row">
        <div class="col-xs-12">
            <h2 class="page-header">
                <i class="fa fa-globe"></i> 变更详情页
                <small class="pull-right">创建时间: {{ change.dt_created }}</small>
            </h2>
        </div>
        <!-- /.col -->
    </div>
    <!-- info row -->
    {{ form.as_p }}
    <!-- /.row -->

    <!-- this row will not appear when printing -->
    <div class="row no-print">
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary pull-right" style="margin-right: 5px;">
                <i class="fa fa-submit"></i> 提交
            </button>
            <button type="submit" class="btn btn-primary pull-right" style="margin-right: 5px;">
                <i class="fa fa-save"></i> 保存
            </button>
        </div>
    </div>
    </form>
</section>
{% endblock %}
{% block messages %}
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
{% endif %}
{% endblock %}

src/OMPService/templates/itsm/new_event_detail.html
{% extends "base.html" %}
{% block head %}
    <script src="/static/bower_components/ckeditor/ckeditor.js"></script>
    <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <script src="/static/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('editor1')
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>


{% endblock %}
{% block header %}
    <li class="active">{{ page_header }}</li>
{% endblock %}
{% block content %}
{% if messages %}
    {% for message in messages %}
            {% include "itsm/log_errors.html" %}
    {% endfor %}
{% endif %}
<section class="invoice">
    <!-- title row -->
    <form class="bs-example bs-example-form" role="form" action="/itsm/events/add/" method="POST">{% csrf_token %}
    <div class="row">
        <div class="col-xs-12">
            <h2 class="page-header">
                <i class="fa fa-globe"></i> 事件详情页
                <small class="pull-right">创建时间: {{ event.dt_created }}</small>
            </h2>
        </div>
        <!-- /.col -->
    </div>
    <!-- info row -->
    {{ form.as_p }}
    <!-- /.row -->

    <!-- this row will not appear when printing -->
    <div class="row no-print">
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary pull-right" style="margin-right: 5px;">
                <i class="fa fa-save"></i> 保存
            </button>
        </div>
    </div>
    </form>
</section>
{% endblock %}